### ISSUE TITLE
API key 노출 알림

### ISSUE THREAD

**Issue by qqq1212341** [kucc/kubook-backend#1]
안녕하세요 ! 제 메일에 firebase 계정이 연결되어 있는데, API 노출 알림이 와서 노파심에 알려드리려고 작성합니다.

https://github.com/kucc/kubook-backend/blob/081d2bc20e8ab3b45bf7449cc6723c86832eb7a1/src/auth/firebase_login.py 에 키가 노출되었다네요. 환경 변수로 가리시고 이미 올라간 커밋들은 clear 해보는거 어떠실지 말씀 드립니다 ㅎㅎ (https://cobi-98.tistory.com/48)

좋은 프로젝트 되세요 !!

**Comment by mjkweon17** [comment]
안녕하세요! 키를 노출시킨 점 정말 죄송합니다.
당일에 키 수정과 해당 키를 사용하는 타프로젝트의 키도 수정 도와주신 점 정말 감사합니다.
해당 이슈를 오늘 확인해서 같이 첨부해주신 링크도 실행해봤는데 GitHub에서는 삭제가 안되는 것 같습니다.
당일에 키를 올리자마자 바로 실수를 인지하고 reset 시켜서 commit 기록은 삭제했는데, 이미 GitHub에 올라간 내용은 삭제할 수 없다고 합니다.
아래 링크에서도 GitHub에 올라간 내용은 삭제할 수 없고, 아예 repository를 삭제하고 새로 만드는 방법을 사용해야 할 것 같다고 합니다.
https://www.reddit.com/r/git/comments/mq9wh2/is_there_any_way_to_permanently_remove_commits/
좋은 조언과 도움 주셔서 다시 한 번 감사드리고 앞으로는 이런 일 발생하지 않도록 보안 관리에 더욱 신경 쓰겠습니다.
